# プロデューサー → マネージャー タスク受け取り

このファイルは、プロデューサーがマネージャーに指示を与えるために使用します。

## 指示フォーマット

```yaml
task_id: "task_001"
command: "作業の概要"
description: "作業の詳細説明"
deadline: "2026-02-05 18:00:00"
priority: "high" # high, normal, low
notes: "追加の注記（あれば）"
```

## 例

```yaml
# ノクチル全体のセットアップテスト
task_id: "test_001"
command: "システム全体の動作確認"
description: |
  以下の動作を確認してください：
  1. マネージャーが全アイドルにタスクを分配できることを確認
  2. 各アイドルが独立して作業できることを確認
  3. 報告システムが正常に動作することを確認
  4. ダッシュボードが更新されることを確認
deadline: "2026-02-05 17:00:00"
priority: "high"
notes: "初期テストです。細部は柔軟に対応ください。"
```

**管理者からの指示があるまで、このファイルは変更されません。**
